[package]

name = "estree"
version = "0.0.3"
authors = ["Dave Herman <dherman@mozilla.com>"]
license = "MIT"
description = "A deserializer for the ESTree format."
repository = "https://github.com/dherman/esprit"

[dependencies]
serde = "0.7.0"
serde_json = "0.7.0"
unjson = { version = "0.0.3", path = "../unjson" }
joker = { version = "0.0.3", path = "../joker" }
easter = { version = "0.0.3", path = "../easter" }
