[package]

name = "esprit"
version = "0.0.3"
authors = ["Dave Herman <dherman@mozilla.com>"]
build = "build.rs"
license = "MIT"
description = "An ECMAScript parser library."
repository = "https://github.com/dherman/esprit"
exclude = ["test/build/**/*"]

[dependencies]
serde = "0.7.0"
serde_json = "0.7.0"
unjson = { version = "0.0.3", path = "crates/unjson" }
joker = { version = "0.0.3", path = "crates/joker" }
easter = { version = "0.0.3", path = "crates/easter" }
estree = { version = "0.0.3", path = "crates/estree" }
