[package]

name = "joker"
version = "0.0.3"
authors = ["Dave Herman <dherman@mozilla.com>"]
license = "MIT"
description = "A JavaScript tokenizer."
repository = "https://github.com/dherman/esprit"

[dependencies]
serde_json = "0.7.0"
unjson = { version = "0.0.3", path = "../unjson" }
